### PR TITLE
Update to v0.26.0

### LINKED ISSUE #14: Release v0.26.0
The latest libgit2 release is v0.26.0.

### PR DESCRIPTION
**Pull request by dfornika**
Fixes #14.

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
@conda-forge-admin, please rerender

**Comment by shadowwalkersb** [comment]
@conda-forge/core , need help fixing py35 failures on Appveyor! 

https://ci.appveyor.com/project/conda-forge/libgit2-feedstock/build/1.0.52/job/g23hqbnjqt03ccqm 
https://ci.appveyor.com/project/conda-forge/libgit2-feedstock/build/1.0.52/job/j0bghkrvccrblnnl.

**Comment by isuruf** [comment]
@kalefranz, do you know why conda 4.3.30 fails installing a noarch package?

**Comment by kalefranz** [comment]
That looks like https://github.com/conda/conda/issues/6057, which was fixed in https://github.com/conda/conda/pull/6277, released in 4.3.32.

**Comment by dfornika** [comment]
Is there some way we can bump the failing builds (python 3.5 on x86 and x64) to conda 4.3.32?

**Comment by isuruf** [comment]
@dfornika, restarting should fix it

**Comment by shadowwalkersb** [comment]
@isuruf , I thought you moved the builds from this PR under 'broken' label. Restarting Appveyor would fix only Windows, or would it?

**Comment by isuruf** [comment]
@shadowwalkersb, no I removed the broken `conda-forge-build-setup` packages. restarting appveyor should fix the error. packages from this PR are not yet uploaded

**Comment by jakirkham** [comment]
Do we have an issue tracking the cause of the breakage? Sorry if this is an obvious answer, missed some of the dialogue at that time.

**Comment by shadowwalkersb** [comment]
Well, I am lost following the conversation here. Not sure why there was a conversation about noarch packages here. I thought it was related to the breakage.

Appveyor tests passed, but GitHub still shows it as pending... Shall I merge regardless of that?

**Comment by jakirkham** [comment]
Yeah `conda-forge-build-setup` was broken somehow. Also missed the `noarch` part too. In any event, that convo can be ignored as far as this PR is concerned.

Sure. That probably means AppVeyor got rate limited by GitHub and so couldn't update the status.

**Comment by jakirkham** [comment]
Though we might want to check the pinnings before merging.

**Comment by jakirkham** [comment]
@dfornika, could you please change the following...

* `curl` -> `curl >=7.44.0,<8`
* `libiconv` -> `libiconv 1.15` (added in edit)
* `libssh2` -> `libssh2 1.8.*`

**Comment by jakirkham** [comment]
Also added `libiconv` in the edit. Sorry about that.

**Comment by shadowwalkersb** [comment]
Thanks @dfornika for the PR! Merging...

**Pull request merged**
