### PR TITLE
updated to v0.24.5

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
Hi @jakirkham !

Are You the maintainer of this feedstock?
Appveyor still pending, what can I do against it?

**Comment by jakirkham** [comment]
Nope I'm not maintaining this one. That falls to @shadowwalkersb .

AppVeyor had some issues that appear to have been resolved. Though I think this needs a [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.7.0` before this can proceed. Could you please give that a try?

**Comment by shadowwalkersb** [comment]
CircleCI is still not triggered.

**Comment by kszucs** [comment]
Why is that? Is the hook enabled?
I don't have the permissions to try this workaround https://discuss.circleci.com/t/github-pushes-not-triggering-builds/722

**Comment by kszucs** [comment]
Conda forge issue about circle-ci [PR Builds not starting](https://github.com/conda-forge/status/issues/30)

**Comment by jakirkham** [comment]
So you can enable CircleCI on your fork @kszucs . Would give that a try.

**Comment by kszucs** [comment]
Done https://github.com/kszucs/libgit2-feedstock/branches 

Is it OK to merge now?

**Comment by kszucs** [comment]
How much effort would it take to create pygit2-feedstock? I've not found a guide about creating a feedstock from a pip installable package yet.

**Comment by shadowwalkersb** [comment]
Take a look at this for new feedstocks https://conda-forge.github.io/#add_recipe.

**Pull request merged**
