### PR TITLE
add build and run req: libssh2

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
[CicleCI problems](https://circleci.com/gh/shadowwalkersb/libgit2-feedstock/34):
1. Can't find `libssh2`
   
   ```
    -- Checking for module 'libssh2'
    --   No package 'libssh2' found
    -- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
   ```
2. Package upload fail
   
   ```
   Adding distribution /feedstock_root/build_artefacts/linux-64/libgit2-0.24.1-0.tar.bz2 to conda-forge's main channel
   Traceback (most recent call last):
     File "/opt/conda/bin/upload_or_check_non_existence", line 140, in <module>
       main()
     File "/opt/conda/bin/upload_or_check_non_existence", line 129, in main
       add_distribution_to_channel(cli, meta, owner, channel)
     File "/opt/conda/bin/upload_or_check_non_existence", line 98, in add_distribution_to_channel
       binstar_cli.add_channel(channel, owner, meta.name(), meta.version())
     File "/opt/conda/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 47, in add_channel
       self._check_response(res, [201])
     File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
       raise ErrCls(msg, res.status_code)
   binstar_client.errors.NotFound: ('you do not have write permissions to package conda-forge/libgit2', 404)
   ```

**Comment by shadowwalkersb** [comment]
>  Package upload fail
> 
> Adding distribution /feedstock_root/build_artefacts/linux-64/libgit2-0.24.1-0.tar.bz2 to conda-forge's main channel
> Traceback (most recent call last):
>   File "/opt/conda/bin/upload_or_check_non_existence", line 140, in <module>
>     main()
>   File "/opt/conda/bin/upload_or_check_non_existence", line 129, in main
>     add_distribution_to_channel(cli, meta, owner, channel)
>   File "/opt/conda/bin/upload_or_check_non_existence", line 98, in add_distribution_to_channel
>     binstar_cli.add_channel(channel, owner, meta.name(), meta.version())
>   File "/opt/conda/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 47, in add_channel
>     self._check_response(res, [201])
>   File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
>     raise ErrCls(msg, res.status_code)
> binstar_client.errors.NotFound: ('you do not have write permissions to package conda-forge/libgit2', 404)

<del>Hope PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/39 ) will fix this.</del>

**Comment by jakirkham** [comment]
Ditto.

xref: https://github.com/conda-forge/libssh2-feedstock/pull/2#issuecomment-255638866

**Comment by shadowwalkersb** [comment]
Still, cmake can't find `libssh2`. Also, `HTTP_Parser` can't be found. Is that a concern? I haven't even checked if `conda-forge` has it?

```
-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
-- http-parser was not found or is too old; using bundled 3rd-party sources.
...
-- Checking for module 'libssh2'
--   No package 'libssh2' found
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
```

**Comment by jakirkham** [comment]
Sorry, I don't have bandwidth to dig into this.

**Comment by shadowwalkersb** [comment]
`MemoryError` on [appveyor](https://ci.appveyor.com/project/conda-forge/libgit2-feedstock/build/1.0.5/job/wcfvgb94ajwkpx8l#L144). Maybe, it is a conda issue?

When `HTTP_Parser` is not found, the bundled version is used. So, ignoring it.

Fixing `libssh2 not found` will require patching CMakeLists. Since, it is optional, ignoring it, too.

Other than those, this should be good to merge?

**Comment by shadowwalkersb** [comment]
After deleting the fork this PR originated from this thread became inactive. The work continues in #8 and this will be closed. Some of the problems mentioned here:
- Upload to CircleCI fails. **Solved.**
- `MemoryError`. **Not valid anymore.**
- `HTTP_Parser` is not found. **Ignored.**
- `libssh2 not found`. **Delegated to #8 .**

**Pull request closed without merging**
