### PR TITLE
add build and run req: libssh2

### PR DESCRIPTION
**Pull request by shadowwalkersb**
Superceeds and closes #2 .

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
Upload problem mentioned in https://github.com/conda-forge/libgit2-feedstock/pull/2#issuecomment-254885011 is solved by removing the personal `BINSTAR_TOKEN` environment variable from CircleCI account.

**Comment by shadowwalkersb** [comment]
`No package 'libssh2' found` mentioned in https://github.com/conda-forge/libgit2-feedstock/pull/2#issuecomment-254885011 and https://github.com/conda-forge/libgit2-feedstock/pull/2#issuecomment-255646577 still exists. Suspect `pkgconfig` related issue in libssh2. Will investigate libssh2-feedstock.

**Comment by shadowwalkersb** [comment]
I triggered CI before the fixed libssh2 was built on Travis thinking that Travis wouldn't build this PR before libssh2 anyways. Plus, Travis did not have problems and it is CircleCI we are curious about. Now, I see this on CicleCI

```
-- Checking for module 'libssh2'
--   Found libssh2, version 1.7.0_DEV
```
What is `_DEV` suffix? Why do we see it? 😕

**Comment by shadowwalkersb** [comment]
> What is _DEV suffix? Why do we see it? 😕

See https://github.com/conda-forge/libssh2-feedstock/pull/4#issuecomment-271057053.

**Comment by shadowwalkersb** [comment]
As is libssh2 can be found on Travis and Circle builds, but not on Windows for libgit2 builds on my forks. When the builds are done here I'll double-check and will leave Windows builds alone. Thoughts?

**Comment by jakirkham** [comment]
Unrelated FYI have enabled CircleCI to build PRs on this repo. So it should no longer be necessary to have CircleCI enabled on your fork.

**Pull request merged**
