### PR TITLE
updated to v0.25.0; removed version_tag

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
Looks good to me. Waiting on feedback on a related PR ( #6 ).

**Comment by shadowwalkersb** [comment]
@kszucs , can yo rerender, please?

**Comment by kszucs** [comment]
I'm not familiar with conda forge - yet :)

**Review by shadowwalkersb — APPROVED** [review]

**Comment by kszucs** [comment]
Appveyor can't find conda, any ideas?

**Comment by ocefpaf** [comment]
That is due to a bug in the latest AppVeyor update. They are working on it.

On Dec 31, 2016 8:43 AM, "Krisztián Szűcs" <notifications@github.com> wrote:

Appveyor can't find conda, any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/libgit2-feedstock/pull/7#issuecomment-269861420>,
or mute the thread

**Comment by kszucs** [comment]
Meanwhile I'm creating https://github.com/kszucs/staged-recipes/blob/master/recipes/pygit2/meta.yaml

Would You check it please?
Can I add You as a maintainer?

**Comment by shadowwalkersb** [comment]
You can add me as maintainer.

**Comment by shadowwalkersb** [comment]
Thanks, @kszucs !

**Pull request merged**
